# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode7.3
rvm:
  - 2.2.2
cache: cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod update --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -workspace Example/Pbind.xcworkspace -scheme Pbind-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
