# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode7.3
language: objective-c
rvm:
  - 2.2.5 
#cache: cocoapods
podfile: Example/Podfile
before_install:
  - sw_vers # Show osx versions
  - gen cleanup cocoapods
  - gem uninstall cocoapods
  - gem install cocoapods --pre
#  - pod repo update MBProgressHUD # The Travis repo are TOO old?
  - pod install --project-directory=Example
script:
  - xctool test -workspace Example/Pbind.xcworkspace -scheme Pbind-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO
  - pod lib lint
